apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-client
  labels:
    app: order-client
    version: v1.17
spec:
  replicas: 1
  template:
    metadata:
      name: order-client
      labels:
        app: order-client
        app.kubernetes.io/name: order-client
        app.kubernetes.io/version: v1.17
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order-client"
        dapr.io/app-port: "8080"
        prometheus.io/scrape: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
        - name: order-client
          image: vincentfree/order-client:v1.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DAPR_ACTIVE
              value: "true"
          resources:
            requests:
              memory: 300Mi
              cpu: 150m
            limits:
              memory: 800Mi
              cpu: 1000m
      restartPolicy: Always
  selector:
    matchLabels:
      app: order-client
---
apiVersion: v1
kind: Service
metadata:
  name: order-client
  labels:
    app.kubernetes.io/name: order-client
    app.kubernetes.io/version: v1.17
spec:
  selector:
    app: order-client
  ports:
    - port: 8080
      protocol: TCP
  type: ClusterIP