apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dapr
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"
    - name: authRequired
      value: "false"
    # - name: saslUsername
    #   value: "adminuser"
    # - name: saslPassword
    #   value: "KeFg23!"
    - name: maxMessageBytes
      value: 1024