apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongo-state-store
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: 'dapr-mongodb.traffic-generation-apps.svc.cluster.local:27017' # Required. Example: "mongo-mongodb.default.svc.cluster.local:27017"
    - name: username
      value: admin # Optional. Example: "admin"
    - name: password
      secretKeyRef:
        name: dapr-mongodb
        key: mongodb-root-password
#    - name: databaseName
#      value: <REPLACE-WITH-DATABASE-NAME> # Optional. default: "daprStore"
#    - name: collectionName
#      value: <REPLACE-WITH-COLLECTION-NAME> # Optional. default: "daprCollection"
#    - name: writeconcern
#      value: <REPLACE-WITH-WRITE-CONCERN> # Optional.
#    - name: readconcern
#      value: <REPLACE-WITH-READ-CONCERN> # Optional.
#    - name: operationTimeout
#      value: <REPLACE-WITH-OPERATION-TIMEOUT> # Optional. default: "5s"
